name: UserDataFetcher
description: A new Dart project to fetch and process user data.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  logging: ^1.0.2

dev_dependencies:
  test: ^1.16.0
